### ISSUE TITLE
Error al cargar favoritos

### ISSUE THREAD

**Issue by jampueroc** [yamillanz/guayanamap#2]
Los favoritos se cargan en el select pero no se muestran en el mapa.
![Captura de Pantalla 2022-08-01 a la(s) 12 09 16](https://user-images.githubusercontent.com/9870984/182192418-b65b01ca-4b5d-4e80-b9cd-cd57dfc2be05.png)
 

Al revisar la consola aparece un problema con los datos
![Captura de Pantalla 2022-08-01 a la(s) 12 05 47](https://user-images.githubusercontent.com/9870984/182192546-50e9de12-bdbb-4c26-9d1e-77510c4c1b19.png)

Te recomiendo usar [angularFire](https://github.com/angular/angularfire) para conexión con la base de datos.

**Comment by yamillanz** [comment]
Agregado un validacion y el angular Fire

**Comment by jampueroc** [comment]
Aún no carga favoritos, usaste firestore en ves de realtime database.

- [ ]  Para guardar datos sigues usando http en ves de angularFire: https://github.com/angular/angularfire/blob/master/docs/rtdb/objects.md#saving-data
- [ ] Para desplegar los favoritos: https://github.com/angular/angularfire/blob/master/docs/rtdb/lists.md

**Comment by yamillanz** [comment]
Ok ya lo cambio de nuevo a una RealTime DataBase...
Para cargar los favoritos debes colocar algo que te devuelva un data (le coloce esa validacion)...si escribes "asdqwdqwd" o "wwww" no te agregar...coloca cosas como "LLovizna" o "Orinokia" lugares turistico

**Comment by yamillanz** [comment]
Listo...modificado para que apunte a unas realtime databases

Gracias por los enlaces a la doc...
